name: Geecodex
description: "A Codex For Geeks"

publish_to: 'none' 

version: 0.0.3+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_pdfview: ^1.2.2
  http: ^1.3.0
  file_picker: ^10.1.9 
  shared_preferences: ^2.5.2
  intl: ^0.20.2
  image_picker: ^1.1.2

  dio: ^5.3.2
  get_it: ^7.6.0

  syncfusion_flutter_pdfviewer: ^28.2.11
  pdf_combiner: 4.3.3
  path: ^1.9.0
  url_launcher: ^6.3.0

  convex_bottom_bar: ^3.2.0
  ffi: ^2.1.4
  path_provider: ^2.0.11
  carousel_slider: ^5.0.0

  permission_handler: ^11.0.0

  device_info_plus: ^11.4.0
  package_info_plus: ^8.3.0


  flutter_heatmap_calendar: ^1.0.5


flutter_launcher_icons: 
  android: "launcher_icon"
  image_path: "lib/assets/star.jpg"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  

flutter:
  uses-material-design: true
  
  generate: true

  assets:
    - lib/assets/
